apps/planted_trees/urls.py
from django.urls import path
from apps.planted_trees.views import home_view, my_accounts, planted_tree_detail_view, PlantedTreeCreateView

app_name = 'planted_trees'

urlpatterns = [
    path('home/', home_view, name='home'),
    path('my_accounts/', my_accounts, name='my_accounts'),
    path('<int:id>/', planted_tree_detail_view, name='planted_tree_detail'),
    path('add/', PlantedTreeCreateView.as_view(), name='planted_tree_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
    path('planted_trees/', include('apps.planted_trees.urls')),
]

apps/planted_trees/models.py
from django.db import models
from apps.users.models import UserProfile
from apps.trees.models import Tree
from apps.accounts.models import Account


class PlantedTree(models.Model):
    """
    Class PlantedTree represents a tree that has been planted by a user.

    Attributes:
    age (int): age of the tree in years.
    planted_at (DateTimeField): date and time when the tree was planted.
    user (ForeignKey): ForeignKey to the UserProfile that planted the tree.
    tree (ForeignKey): ForeignKey to the Tree model representing the species of the tree.
    location (DecimalField): geographical location of the planted tree.
    account (ForeignKey): ForeignKey to the Account model representing the account where the tree was planted.


    Methods:
    str: Returns the string representation of the UserProfile that planted the tree.
    """
    age = models.IntegerField()
    planted_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='planted_trees_by')
    tree = models.ForeignKey(Tree, on_delete=models.CASCADE, related_name='planted_species')
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='planted_trees_in')


    @property
    def location(self):
        return (self.latitude, self.longitude)
        
    def __str__(self):
        return self.tree.name

apps/planted_trees/forms.py
from django import forms
from apps.trees.models import Tree
from apps.planted_trees.models import PlantedTree
from apps.accounts.models import Account

class PlantedTreeForm(forms.ModelForm):
    account = forms.ModelChoiceField(queryset=Account.objects.none())

    class Meta:
        model = PlantedTree
        fields = ['tree', 'age', 'latitude', 'longitude', 'account']
        widgets = {
            'tree': forms.Select(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'latitude': forms.NumberInput(attrs={'class': 'form-control'}),
            'longitude': forms.NumberInput(attrs={'class': 'form-control'}),
            'account': forms.Select(attrs={'class': 'form-control'}),

        }
    
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tree'].queryset = Tree.objects.all()
        self.fields['account'].queryset = Account.objects.filter(users=user)

apps/planted_trees/views.py
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from apps.planted_trees.forms import PlantedTreeForm
from apps.trees.models import Tree
from apps.planted_trees.models import PlantedTree
from apps.users.models import UserProfile

@login_required
def home_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    planted_trees = PlantedTree.objects.filter(user=user_profile)
    return render(request, 'planted_trees.html', {'planted_trees': planted_trees})


@login_required
def my_accounts(request):
    accounts = request.user.userprofile.accounts.all()
    planted_trees = PlantedTree.objects.filter(account__in=accounts)
    planted_trees = planted_trees.filter(user=request.user.userprofile)

    context = {'planted_trees': planted_trees}
    return render(request, 'my_accounts.html', context)


@login_required
def planted_tree_detail_view(request, id):
    user_profile = UserProfile.objects.get(user=request.user)
    tree = get_object_or_404(PlantedTree, id=id, user=user_profile)
    return render(request, 'planted_tree_detail.html', {'tree': tree})


class PlantedTreeCreateView(CreateView):
    model = PlantedTree
    form_class = PlantedTreeForm
    template_name = 'planted_tree_create.html'
    success_url = reverse_lazy('planted_trees:home')
    
    def form_valid(self, form):
        form.instance.user = self.request.user.userprofile
        return super().form_valid(form)
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['tree'].queryset = Tree.objects.all()
        form.fields['account'].queryset = self.request.user.userprofile.accounts.all()
        return form
        
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user.userprofile
        return kwargs

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Minha Aplicação</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Árvores Plantadas</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'planted_trees:my_accounts' %}">Minha Comunidade</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sair</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/my_accounts.html
{% extends 'base.html' %}

{% block content %}
  <h1>Minhas Árvores</h1>
  {% if planted_trees %}
    <table class="table">
      <thead>
        <tr>
          <th>Espécie</th>
          <th>Data de plantio</th>
        </tr>
      </thead>
      <tbody>
        {% for tree in planted_trees %}
          <tr>
            <td>{{ tree.tree.name }}</td>
            <td>{{ tree.planted_at|date:'d/m/Y' }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Nenhuma árvore plantada por sua comunidade :/</p>
  {% endif %}
{% endblock %}

templates/planted_tree_create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Cadastrar árvore plantada</h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Salvar</button>
    <a href="{% url 'planted_trees:home' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock %}

templates/planted_tree_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>{{ tree.tree.name }}</h1>
      <table class="table">
        <tr>
          <th>Idade:</th>
          <td>{{ tree.age }}</td>
        </tr>
        <tr>
          <th>Nome Científico:</th>
          <td>{{ tree.tree.scientific_name }}</td>
        </tr>
        <tr>
          <th>Data de plantio:</th>
          <td>{{ tree.planted_at|date:'d/m/Y H:i:s' }}</td>
        </tr>
        <tr>
          <th>Latitude:</th>
          <td>{{ tree.latitude }}</td>
        </tr>
        <tr>
          <th>Longitude:</th>
          <td>{{ tree.longitude }}</td>
        </tr>
      </table>
      <a href="{% url 'planted_trees:home' %}" class="btn btn-secondary">Voltar</a>
    </div>
  </div>
{% endblock %}

templates/planted_trees.html
{% extends 'base.html' %}

{% block content %}
  <h1>Minhas Árvores</h1>
  <a href="{% url 'planted_trees:planted_tree_create' %}" class="btn btn-success">Plantar uma Árvore</a>
  {% if planted_trees %}
    <table class="table">
      <thead>
        <tr>
          <th>Espécie</th>
          <th>Data de plantio</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for tree in planted_trees %}
          <tr>
            <td>{{ tree.tree.name }}</td>
            <td>{{ tree.planted_at|date:'d/m/Y' }}</td>
            <td><a href="{% url 'planted_trees:planted_tree_detail' id=tree.id %}">Detalhes</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Você ainda não plantou nenhuma árvore.</p>
  {% endif %}
{% endblock %}